---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
spec:
  secretName: ca-cert
  duration: 87600h
  renewBefore: 360h
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  commonName: cacert
  dnsNames:
  - caroot
  issuerRef:
    name: selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-server
spec:
  privateKey:
    encoding: PKCS8
  secretName: zookeeper-server-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
  - zookeeper-0.zuul-cs.svc.cluster.local
  - zookeeper-0
  issuerRef:
    name: ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-client-tls
  labels:
    app.kubernetes.io/name: zookeeper-client-certificate
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zookeeper-client-certificate
spec:
  privateKey:
    encoding: PKCS8
  secretName: zookeeper-client-tls
  commonName: client
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: ca-issuer
    kind: Issuer